name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
    hello-job:
      name: hello-job
      runs-on: ubuntu-latest
      steps:
      - name: Echo text
        run: echo "Hello, world!"
